import Layout from "../../../components/layout/layout";

const Privacy = props => (
  <Layout>
    <div className="container" style={{ overflowX: "hidden" }}>
      <section>
        <h2>Twake Privacy Policy</h2>
        <br />
        <br />
        Our Privacy Policy was posted on 1 September 2019. It governs the
        privacy terms of our website, located at twakeapp.com, and the tools we
        provide you (the "Website" or the “Service") including the desktop,
        mobile and browser Twake application. Any capitalized terms not defined
        in our Privacy Policy, have the meaning as specified in our Terms of Use
        accessible at{" "}
        <a href="https://twake.app/files/tos.md" target="_BLANK">
          https://twake.app/files/tos.md
        </a>
        <br />
        Your Privacy
        <br />
        Our Website follows all legal requirements to protect your privacy. Our
        Privacy Policy is a legal statement that explains how we may collect
        information from you, how we may share your information, and how you can
        limit our sharing of your information. You will see terms in our Privacy
        Policy that are capitalized. These terms have meanings as described in
        the Definitions section below.
        <br />
        <br />
        <h3>Definitions</h3>• <b>Personal Data</b>: Personal Data means data
        about a living individual who can be identified from those data (or from
        those and other information either in our possession or likely to come
        into our possession).
        <br />• <b>Usage Data</b>: Usage Data is data collected automatically
        either generated by the use of the Service or from the Service
        infrastructure itself (for example, the duration of a page visit).
        <br />• <b>Cookies</b>: Cookies are small pieces of data stored on a
        User's device.
        <br />• <b>Service Generated Data</b>: Service Generated Data means the
        data created, edited or uploaded on our service. It includes messages,
        events, documents, projects, architecture of your workspaces and
        everything needed to run our Service.
        <br />• <b>Data Controller</b>: Data Controller means a natural or legal
        person who (either alone or jointly or in common with other persons)
        determines the purposes for which and the manner in which any personal
        data are, or are to be, processed. For the purpose of this Privacy
        Policy, we are a Data Controller of your data.
        <br />• <b>Data Processors</b> (or Service Providers): Data Processor
        (or Service Provider) means any natural or legal person who processes
        the data on behalf of the Data Controller. We may use the services of
        various Service Providers in order to process your data more
        effectively.
        <br />• <b>Data Subject</b>: Data Subject is any living individual who
        is the subject of Personal Data.
        <br />• <b>User</b>: The User is the individual using our Service. The
        User corresponds to the Data Subject, who is the subject of Personal
        Data.
        <br />
        <br />
        <h3>Information Collection And Use</h3>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
        <br />
        <br />
        <h5>Types of Data Collected</h5>• <b>Personal Data</b>
        <br />
         While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you ("Personal Data"). Personally identifiable information may
        include: Email address, Name, Phone number and Cookies.
        <br />
         We may use your Personal Data to contact you with newsletters,
        marketing or promotional materials and other information that may be of
        interest to you. You may opt out of receiving any, or all, of these
        communications from us by following the unsubscribe link or instructions
        provided in any email we send.
        <br />  • <b>Usage Data</b>
        <br />
         We may also collect information how the Service is accessed and used
        ("Usage Data"). This Usage Data may include information such as your
        computer's Internet Protocol address (e.g. IP address), browser type,
        browser version, the pages of our Service that you visit, the time and
        date of your visit, the time spent on those pages, unique device
        identifiers and other diagnostic data.
        <br />  • <b>Tracking & Cookies Data</b>
        <br />
         We use cookies and similar tracking technologies to track the activity
        on our Service and hold certain information.
        <br />
         Cookies are files with small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Tracking technologies also used are
        beacons, tags, and scripts to collect and track information and to
        improve and analyze our Service.
        <br />
         You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use our Service.
        <br />
         Examples of Cookies we use: session cookies (we use these cookies to
        operate our Service).
        <br />
         
        <br />
        <h3>Use of Data</h3>
        We use the collected data for various purposes: • To provide and
        maintain our Service
        <br />
        • To notify you about changes to our Service
        <br />
        • To allow you to participate in interactive features of our Service
        when you choose to do so
        <br />
        • To provide customer support
        <br />
        • To gather analysis or valuable information so that we can improve our
        Service
        <br />
        • To monitor the usage of our Service
        <br />
        • To detect, prevent and address technical issues
        <br />
        • To provide you with news, special offers and general information about
        other goods, services and events which we offer that are similar to
        those that you have already purchased or enquired about unless you have
        opted not to receive such information
        <br />
        <br />
        <h3>Retention of Data</h3>
        We will retain your Personal Data only for as long as is necessary for
        the purposes set out in this Privacy Policy. We will retain and use your
        Personal Data to the extent necessary to comply with our legal
        obligations (for example, if we are required to retain your data to
        comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies.
        <br />
        We will also retain Usage Data for internal analysis purposes. Usage
        Data is generally retained for a shorter period of time, except when
        this data is used to strengthen the security or to improve the
        functionality of our Service, or we are legally obligated to retain this
        data for longer time periods.
        <br />
        <br />
        <h3>Transfer Of Data</h3>
        Your information, including Personal Data, may be transferred to — and
        maintained on — computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ than those from your jurisdiction.
        <br />
        Your information, including Personal Data and Service Generated Data, is
        encrypted and cannot be read by a tier.
        <br />
        Your Usage Data is not encrypted and is transferred to tier.
        <br />
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
        <br />
        <br />
        <h3>Disclosure Of Data</h3>• <b>Business Transaction</b>. If we are
        involved in a merger, acquisition or asset sale, your Personal Data may
        be transferred. We will provide notice before your Personal Data is
        transferred and becomes subject to a different Privacy Policy.
        <br />• <b>Disclosure for Law Enforcement</b>. Under certain
        circumstances, we may be required to disclose your Personal Data if
        required to do so by law or in response to valid requests by public
        authorities (e.g. a court or a government agency).
        <br />
        <br />
        <h3>Security Of Data</h3>
        Service Generated Data is always encrypted and cannot be read by tiers.
        You can read more about how we secure your data on twakeapp.com .<br />
        Legal Basis for Processing Personal Data Under General Data Protection
        Regulation (GDPR) If you are from the European Economic Area (EEA),
        Twake legal basis for collecting and using the personal information
        described in this Privacy Policy depends on the Personal Data we collect
        and the specific context in which we collect it.
        <br />
        Twake may process your Personal Data because: • We need to perform a
        contract with you
        <br />
        • You have given us permission to do so
        <br />
        • The processing is in our legitimate interests and it's not overridden
        by your rights
        <br />
        • For payment processing purposes
        <br />
        • To comply with the law
        <br />
        <br />
        <h3>
          Your Data Protection Rights Under General Data Protection Regulation
          (GDPR)
        </h3>
        If you are a resident of the European Economic Area (EEA), you have
        certain data protection rights. Twake aims to take reasonable steps to
        allow you to correct, amend, delete, or limit the use of your Personal
        Data.
        <br />
        If you wish to be informed what Personal Data we hold about you and if
        you want it to be removed from our systems, please contact us.
        <br />
        In certain circumstances, you have the following data protection rights:
        • The right to access, update or to delete the information we have on
        you.
        <br />
        • The right of rectification. You have the right to have your
        information rectified if that information is inaccurate or incomplete.
        <br />
        • The right to object. You have the right to object to our processing of
        your Personal Data.
        <br />
        • The right of restriction. You have the right to request that we
        restrict the processing of your personal information.
        <br />
        • The right to data portability. You have the right to be provided with
        a copy of your Personal Data in a structured, machine-readable and
        commonly used format.
        <br />
        • The right to withdraw consent. You also have the right to withdraw
        your consent at any time where Twake relied on your consent to process
        your personal information.
        <br />
          Please note that we may ask you to verify your identity before
        responding to such requests.
        <br />
        You have the right to complain to a Data Protection Authority about our
        collection and use of your Personal Data. For more information, please
        contact your local data protection authority in the European Economic
        Area (EEA).
        <br />
        <br />
        <h3>Service Providers</h3>
        We may employ third party companies and individuals to facilitate our
        Service ("Service Providers"), to provide the Service on our behalf, to
        perform Service-related services or to assist us in analyzing how our
        Service is used.
        <br />
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
        <br />
        <br />
        <h5>Analytics</h5>
        We may use third-party Service Providers to monitor and analyze the use
        of our Service.
        <br />• <b>Google Analytics</b>
        <br />
         Google Analytics is a web analytics service offered by Google that
        tracks and reports website traffic. Google uses the data collected to
        track and monitor the use of our Service. This data is shared with other
        Google services. Google may use the collected data to contextualize and
        personalize the ads of its own advertising network.
        <br />
         You can opt-out of having made your activity on the Service available
        to Google Analytics by installing the Google Analytics opt-out browser
        add-on. The add-on prevents the Google Analytics JavaScript (ga.js,
        analytics.js, and dc.js) from sharing information with Google Analytics
        about visits activity.
        <br />
         For more information on the privacy practices of Google, please visit
        the Google Privacy & Terms web page :{" "}
        <a href="https://policies.google.com/privacy?hl=en" target="_BLANK">
          https://policies.google.com/privacy?hl=en
        </a>
        <br />• <b>Mixpanel</b>
        <br />
         Mixpanel is a web analytics service offered by Mixpanel and allows us
        to monitor the service usage by application and by user. A common usage
        is the number of daily connected users. For more information visit
        Mixpanel website on{" "}
        <a href="https://mixpanel.com/" target="_BLANK">
          https://mixpanel.com/
        </a>
        <br />
        <br />
        <h5>Storage and cloud services</h5>• <b>Amazon Web Services</b>
        <br />
         Our servers, your documents and your data are stored in the cloud
        provider Amazon Web Services. We deployed our infrastructure in Paris.
        More information on{" "}
        <a href="https://aws.amazon.com" target="_BLANK">
          https://aws.amazon.com
        </a>
        <br />• <b>OVH</b>
        <br />
         Some secondary services can be stored on OVH, also in France. More
        information on{" "}
        <a href="https://ovh.com" target="_BLANK">
          https://ovh.com
        </a>
        <br />
        <br />
        <h3>Usage of Integrations</h3>
        The Service allows you to connect with tier services (for instance
        Google Drive) and so we transfert some part of your Service Generated
        Data and Personal Data to those tiers.
        <br />
        All integrations are optional and you can choose to use or to not use
        them on each Service workspace.
        <br />
        Any activated integration has access to your company name, logo ; your
        workspace name, logo and members ; and has specified capabilities and
        privileges visible before the app activation.
        <br />
        We do not control how data is used once transferred to integrations but
        each transfer initiated by Twake or to Twake must be over HTTPS.
        <br />
        <br />
        <h5>Google Drive integration</h5>
         Google Drive integration synchronise your Twake Drive with a Google
        Drive.
        <br />
        Each file uploaded to Twake is moved to Google Drive and replaced by a
        link to Google Drive in Twake.
        <br />
        Each file uploaded to Google Drive creates a link in Twake.
        <br />
        Documents contents are not stored in Twake but only in Google Drive.
        <br />
        Moving a document from Google Drive or from Twake moves the documents in
        the other Service, including in the trash.
        <br />
        Twake cannot definitively delete a Google Drive file.
        <br />
        The transfer between the two Services is operated over HTTPS, using a
        middle server which user Google Drive API and Twake API.
        <br />
        The middle server (managed by Twake) never store the content of your
        documents and only act as a relay.
        <br />
        The middle server can store metadata of your documents (name, date of
        creation, format, path, last modification, etc) during a limited time to
        avoid change collision and errors.
        <br />
        You can find more information about Google Drive privacy policy on{" "}
        <a href="https://drive.google.com" target="_BLANK">
          https://drive.google.com
        </a>
        <br />
        <br />
        <h5>Zapier / IFTTT integrations</h5>
         Zapier or IFTTT allows you to create automations in your workspace.
        <br />
        Because Zapier or IFTTT can modify a lot of information in your
        workspaces, it has many privileges and capabilities.
        <br />
        A middle server (managed by Twake) is used to connect Zapier or IFTTT to
        Twake and is only used to store the access keys and relay data.
        <br />
        You can read more about Zapier and IFTTT privacy policy on{" "}
        <a href="https://zapier.com" target="_BLANK">
          https://zapier.com
        </a>{" "}
        and{" "}
        <a href="https://ifttt.com/" target="_BLANK">
          https://ifttt.com/
        </a>
        <br />
        <br />
        <h5>General push notifications integrations</h5>
         We provide many integrations to notify you on the Twake Service
        messaging service generally called Webhooks.
        <br />
        Webhooks are only one way and cannot send Service Generated Data to tier
        services.
        <br />
        <br />
        <h5>Twake default integrations</h5>
         We provide some default integrations fully managed and integrated in
        the Twake Service and cannot be considered as tier services.
        <br />
        It includes : Tasks, Documents, Calendar, OnlyOffice, Outcoming
        Webhooks, Jitsi, RSS, Remind and Simple Poll.
        <br />
        <br />
        <h3>Links To Other Sites</h3>
        Our Service may contain links to other sites that are not operated by
        us. If you click on a third party link, you will be directed to that
        third party's site. We strongly advise you to review the Privacy Policy
        of every site you visit.
        <br />
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
        <br />
        <br />
        <h3>Children's Privacy</h3>
        Our Service is not targeted to anyone under the age of 18 ("Children").
        <br />
        We do not knowingly collect personally identifiable information from
        anyone under the age of 18. If you are a parent or guardian and you are
        aware that your Children has provided us with Personal Data, please
        contact us. If we become aware that we have collected Personal Data from
        children without verification of parental consent, we take steps to
        remove that information from our servers.
        <br />
        <br />
        <h3>Changes To This Privacy Policy</h3>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
        <br />
        We will let you know via email and/or a prominent notice on our Service,
        prior to the change becoming effective and update the "effective date"
        at the top of this Privacy Policy.
        <br />
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
        <br />
        <br />
        <h3>Contact Us</h3>
        If you have any questions about this Privacy Policy, please contact us
        on contact@twakeapp.com .<br />
        <br />
        <br />
        <br />
        <hr />
      </section>
    </div>
  </Layout>
);

Privacy.getInitialProps = async () => ({
  locale: "en"
});
export default Privacy;
